package org.codeslu.wpay.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF006D3A)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF4CD080)
val onPrimaryContainerLight = Color(0xFF003C1D)
val secondaryLight = Color(0xFF002429)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF16464D)
val onSecondaryContainerLight = Color(0xFFAFDDE6)
val tertiaryLight = Color(0xFF795835)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFD8B3)
val onTertiaryContainerLight = Color(0xFF5D401F)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF4FBF2)
val onBackgroundLight = Color(0xFF030319)
val surfaceLight = Color(0xFFF4FBF2)
val onSurfaceLight = Color(0xFF161D17)
val surfaceVariantLight = Color(0xFFD8E6D8)
val onSurfaceVariantLight = Color(0xFF3D4A3F)
val outlineLight = Color(0xFF6D7A6E)
val outlineVariantLight = Color(0xFFBCCABC)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2B322C)
val inverseOnSurfaceLight = Color(0xFFECF3E9)
val inversePrimaryLight = Color(0xFF5CDE8D)
val surfaceDimLight = Color(0xFFD5DCD3)
val surfaceBrightLight = Color(0xFFF4FBF2)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEEF6EC)
val surfaceContainerLight = Color(0xFFE9F0E6)
val surfaceContainerHighLight = Color(0xFFE3EAE1)
val surfaceContainerHighestLight = Color(0xFFDDE5DB)
val orange1Light = Color(0xFFFFAE58)
val notificationHeaderColor = Color(0xFF8F92A1)
val segmentedBarBackground = Color(0xFFF2F2F2)
val greenBackgroundLight = Color(0xFF105D38)
val dividerLight = Color(0xFFE0E0E0)
